version: '3'
services:
  browser-use:
    build: .
    ports:
      - "6080:6080"  # noVNC web access
      - "5900:5900"  # VNC
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - .:/app

